Latest version of tink-cli doesnt support `--name`
Remove `--name` for tink template create in vagrant getting started docs. 

Fails:
```
vagrant@provisioner:/vagrant/deploy$ docker exec -i deploy_tink-cli_1 tink template create --name hello-world < ./hello-world.yml
Error: unknown flag: --name
Usage:
  tink template create [flags]

Flags:
      --file string   path to the template file (default "./template.yaml")
  -h, --help          help for create

Global Flags:
  -f, --facility string   used to build grpc and http urls

unknown flag: --name
```

Works:
```
vagrant@provisioner:/vagrant/deploy$ docker exec -i deploy_tink-cli_1 tink template create < ./hello-world.yml
Created Template:  cbc189b4-947f-11eb-ab36-0242ac120005
```